# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as nmp

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(nmp.__version__)
print(nmp.show_config())

1.23.4
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

#### 3. Create a null vector of sivectore 10 (★☆☆)

In [5]:
nullVector = nmp.zeros(10)
print(nullVector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory sivectore of any array (★☆☆)

In [6]:
Memmory_vector_null=nullVector.size*nullVector.itemsize
print(Memmory_vector_null)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of sivectore 10 but the fifth value which is 1 (★☆☆)

In [8]:
vector = nmp.zeros(10)
vector[5] = 1

print(vector)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
vector = nmp.arange(10,50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
first = vector[0]
last = vector[39]

vector[0] = last
vector[39] = first
print(vector)

[49 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
vector = nmp.arange(9).reshape(3,3)

print(vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-vectorero elements from [1,2,0,0,4,0] (★☆☆)

In [16]:
nonZero = nmp.nonzero([1,2,0,0,4,0])

print(nonZero)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [18]:
matrix = nmp.arange(9).reshape(3,3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [20]:
matrix = nmp.random.random((3,3,3))

print(matrix)

[[[0.40193936 0.80664632 0.7293359 ]
  [0.45581043 0.45379848 0.46009462]
  [0.13997308 0.88781419 0.96797509]]

 [[0.8733697  0.95966258 0.05593087]
  [0.70901157 0.57348163 0.00217634]
  [0.72642088 0.25569815 0.02308228]]

 [[0.30281443 0.9799811  0.64765846]
  [0.60338567 0.87811019 0.01532874]
  [0.76232416 0.56178701 0.56486271]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [23]:
matrix = nmp.random.random((10,10))

min, max = matrix.min(), matrix.max()

print(min, max)

0.015055641266375486 0.9869114375598784


#### 14. Create a random vector of sivectore 30 and find the mean value (★☆☆)

In [24]:
vector = nmp.random.random(30)

print(vector.mean())

0.45182188114953786


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [25]:
vector=nmp.ones((3,3))

vector[1:-1,1:-1] = 0

print(vector)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [26]:
vector = nmp.ones((2,2))

vector = nmp.pad(vector, pad_width=1, mode='constant', constant_values=0)

print(vector)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [27]:
print(0 * nmp.nan)
print(nmp.nan == nmp.nan)
print(nmp.inf > nmp.nan)
print(nmp.nan - nmp.nan)
print(nmp.nan in set([nmp.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [29]:
print(nmp.diag( nmp.arange(4), k=-1))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [30]:
board = nmp.zeros((8,8),dtype=int)

board[1::2,::2] = 1
board[::2,1::2] = 1

print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,vector) of the 100th element? (★☆☆)

In [31]:
print(nmp.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [32]:
board = nmp.tile(nmp.array([[0,1],[1,0]]), (4,4))

print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalivectore a 5x5 random matrix (★☆☆)

In [34]:
matrix = nmp.random.random((5,5))

print(vector)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [35]:
customType = nmp.dtype([
    ('r',nmp.ubyte,1),
    ('g', nmp.ubyte, 1),
    ('b', nmp.ubyte, 1),
    ('a', nmp.ubyte, 1)])

print(customType)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\romac\AppData\Local\Temp\ipykernel_9312\3851608873.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  customType = nmp.dtype([


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [37]:
mulMatrix = nmp.dot(nmp.ones((5,3)), nmp.ones((3,2)))

print(mulMatrix)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [41]:
OneDarray = nmp.arange(11)

OneDarray[(3 < OneDarray)&(OneDarray <= 8)]*=-1

print(OneDarray)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [42]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = vector = nmp.zeros((5,5))

#### 28. What are the result of the following expressions? (★☆☆)
```python
nmp.array(0) / nmp.array(0)
nmp.array(0) // nmp.array(0)
nmp.array([nmp.nan]).astype(int).astype(float)
```

In [43]:
nmp.array(0) / nmp.array(0)
nmp.array(0) // nmp.array(0)
nmp.array([nmp.nan]).astype(int).astype(float)

C:\Users\romac\AppData\Local\Temp\ipykernel_9312\1390116473.py:1: RuntimeWarning: invalid value encountered in divide
  nmp.array(0) / nmp.array(0)
C:\Users\romac\AppData\Local\Temp\ipykernel_9312\1390116473.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  nmp.array(0) // nmp.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [44]:
vector = nmp.zeros(10)

vector = nmp.random.uniform(-1,+1,10)

nmp.copysign( nmp.ceil( nmp.abs(vector) ), vector)

array([ 1., -1.,  1.,  1.,  1., -1.,  1.,  1., -1., -1.])

In [ ]:
#### 30. How to find common values between two arrays? (★☆☆)

In [45]:
array1 = [5,6,7,9,10]
array2=[7,-2,4,5,10]

nmp.intersect1d(array1,array2)

array([ 5,  7, 10])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
#nmp(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
nmp.sqrt(-1) == nmp.emath.sqrt(-1)
```

In [46]:
nmp.sqrt(-1) == nmp.emath.sqrt(-1)

C:\Users\romac\AppData\Local\Temp\ipykernel_9312\3316053369.py:1: RuntimeWarning: invalid value encountered in sqrt
  nmp.sqrt(-1) == nmp.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [50]:
yest = nmp.datetime64('today', 'D') - nmp.timedelta64(1, 'D')
tod     = nmp.datetime64('today', 'D')
tom = nmp.datetime64('today', 'D') + nmp.timedelta64(1, 'D')

print(yest, ' ', tod, ' ', tom)

2022-12-05   2022-12-06   2022-12-07


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [52]:
julyDays = nmp.arange('2016-07','2016-08', dtype='datetime64[D]')

print(julyDays)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [53]:
A = 5
B = 6

nmp.multiply(nmp.add(A,B), (nmp.divide( nmp.negative(A),2 )))

-27.5

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [54]:
vector = nmp.random.uniform(0,10,10)

print (vector - vector % 1)
print (nmp.ceil(vector) - 1)
print (vector.astype(int))
print (nmp.trunc(vector))

[7. 9. 3. 9. 6. 8. 2. 3. 4. 5.]
[7. 9. 3. 9. 6. 8. 2. 3. 4. 5.]
[7 9 3 9 6 8 2 3 4 5]
[7. 9. 3. 9. 6. 8. 2. 3. 4. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [56]:
matrix = nmp.zeros((5, 5))
matrix += nmp.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [60]:
def generator():
    for i in range(10): yield i

arr = nmp.fromiter(generator(),dtype=float,count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [64]:
v = nmp.linspace(0, 1, 11, endpoint=False)
print(v)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [65]:
v = nmp.random.random(10)
v.sort()

print(v)

[0.21688699 0.22866521 0.35461339 0.57135135 0.61479143 0.77377934
 0.83902378 0.8591345  0.89408739 0.9276177 ]


#### 41. How to sum a small array faster than nmp.sum? (★★☆)

In [66]:
v = nmp.arange(10)

nmp.add.reduce(v)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [69]:
A=[5,2,3]
B=[5,2,3]

e = nmp.allclose(A,B)
print(e)
e = nmp.array_equal(A,B)
print(e)

True
True


#### 43. Make an array immutable (read-only) (★★☆)

In [72]:
array = nmp.arange(10)
array.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [75]:
matrix = nmp.random.random((10,2))

X,Y = vector[:,1], vector[:,0]

R = nmp.sqrt(X**2 + Y**2)
T = nmp.arctan2(Y, X)

print(R)
print(T)

[0.92682261 1.02299359 0.20228605 0.64561663 0.91687737 1.20476368
 0.91400264 1.2793685  0.92661719 1.22518365]
[0.64074353 0.8354506  0.44836113 0.18178647 1.20164828 0.6124464
 0.438321   0.84252196 0.61379689 0.80983329]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [78]:
vector = nmp.random.random(10)
vector[vector.argmax()] = 0

print(vector)

[0.23861208 0.55066287 0.41229576 0.         0.11569027 0.07674102
 0.35635577 0.64718326 0.76795553 0.55805338]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [79]:
vector = nmp.random.random(10)
print(vector)

[0.42664907 0.70081246 0.16380386 0.98160776 0.9537773  0.06275857
 0.96151275 0.25945005 0.99083387 0.07552503]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [84]:
x = nmp.arange(10)
y = x + 0.5

c = 1 / nmp.subtract.outer(x, y)

print(c)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333 -0.11764706 -0.10526316]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615 -0.13333333 -0.11764706]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818 -0.15384615 -0.13333333]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222 -0.18181818 -0.15384615]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429 -0.22222222 -0.18181818]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.         -0.66666667 -0.4       ]
 [ 0.13333333  0.153846

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [82]:
for scalarType in [nmp.int32, nmp.int64]:
   print(nmp.iinfo(scalarType).min)
   print(nmp.iinfo(scalarType).max)

-2147483648
2147483647
-9223372036854775808
9223372036854775807


#### 49. How to print all the values of an array? (★★☆)

In [83]:
matrix = nmp.arange(10)
print(matrix)

[0 1 2 3 4 5 6 7 8 9]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [85]:
arr = nmp.arange(10)

index = (nmp.abs(arr)).argmin()
print(arr[index])


0


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [90]:


structuredArray = nmp.zeros(20, [ ('pos', [('x', float, 1),('y', float, 1)]),('clr',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])
print(structuredArray)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\romac\AppData\Local\Temp\ipykernel_9312\2230178053.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  structuredArray = nmp.zeros(20, [ ('pos', [('x', float, 1),('y', float, 1)]),('clr',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [91]:
radVector = nmp.random.random((100,2))

x,y = nmp.atleast_2d(radVector[:, 0], radVector[:, 1])
distance = nmp.sqrt( (x - y.T)**2 + (y - y.T)**2)

print(distance)


[[0.20246649 0.22078977 0.19221108 ... 0.37582499 0.1652072  0.63699185]
 [0.41395975 0.31007208 0.21528865 ... 0.32173099 0.25478572 0.39205657]
 [0.43296833 0.32466899 0.22909696 ... 0.32521501 0.27088008 0.3719023 ]
 ...
 [0.67651062 0.53866813 0.4450973  ... 0.45038363 0.49805949 0.12113692]
 [0.37609892 0.28280501 0.1909906  ... 0.3185096  0.22443048 0.43261051]
 [0.76782369 0.62492276 0.53295724 ... 0.52045142 0.58712447 0.03577425]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [92]:

array = nmp.arange(10)
array = array.astype(nmp.int32, copy=False)

print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [93]:
from io import StringIO
f = StringIO('''1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n''')

array = nmp.genfromtxt(f, delimiter=",", dtype=int)
print(array)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [96]:

m = nmp.arange(9).reshape(3,3)
for index, value in nmp.ndenumerate(matrix):
    print(index, value)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 5
(6,) 6
(7,) 7
(8,) 8
(9,) 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [97]:
x, y = nmp.meshgrid(nmp.linspace(-1,1,3), nmp.linspace(-1,1,3))

d = nmp.sqrt(X*X + Y*Y)
sig, m = 1.0, 0.0

gaus = nmp.exp(-( (d-m)**2 / ( 2.0 * sig**2 ) ) )

print(gaus)

[0.65083438 0.59258679 0.97974806 0.81187376 0.65682868 0.48397222
 0.65855949 0.44114049 0.65095829 0.47211273]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [101]:
p = 3

d2 = nmp.zeros((4,4))
nmp.put(d2, nmp.random.choice(range(4*4), 3, replace=False),5)

print(d2)

[[0. 0. 0. 5.]
 [0. 0. 0. 5.]
 [0. 0. 0. 5.]
 [0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [104]:
rows = nmp.random.rand(3, 2)
singlerow = rows - rows.mean(axis=1, keepdims=True)

print(Y)


[[-0.22654951  0.44941558 -0.22286607]
 [ 0.32702551 -0.01976718 -0.30725833]]


#### 59. How to sort an array by the nth column? (★★☆)

In [107]:
array = nmp.random.randint(0,12,(4,4))

print(array)
print(array[array[:,1].argsort()])

[[4 0 5 5]
 [4 1 8 6]
 [0 0 0 1]
 [6 2 1 0]]
[[4 0 5 5]
 [0 0 0 1]
 [4 1 8 6]
 [6 2 1 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [108]:
Darray = nmp.random.randint(0,2,(4,4))

print (Darray)

print((~Darray.any(axis=0)).any())

[[1 0 1 0]
 [0 1 1 1]
 [1 1 1 1]
 [1 0 1 0]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [109]:
matrix = nmp.random.uniform(0, 1, 12)

given = 0.65
near = array.flat[nmp.abs(array - given).argmin()]
print(near)

1


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [110]:
arr1 = nmp.arange(3).reshape(3,1)
arr2 = nmp.arange(3).reshape(1,3)

i = nmp.nditer([array1,array2,None])
for x,y,z in i: z[...] = x + y

print(i.operands[2])

[12  4 11 14 20]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [112]:
v = nmp.ones(10)
s = nmp.random.randint(0,len(v),20)

nmp.add.at(v, s, 1)
print(v)

[2. 3. 3. 1. 5. 5. 2. 3. 4. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [113]:

v = [2, 3, 4, 5, 6, 7]
indexLs = [4, 3, 2, 5, 1, 0]
arr= nmp.bincount(indexLs,v)

print(arr)

[7. 6. 4. 3. 2. 5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [114]:
array = nmp.random.randint(0, 5, (2,3,2,2))

sum = array.sum(axis=(-2,-3))

print(sum)

[[12 16]
 [12  8]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [115]:
import pandas as p;
vector = nmp.random.uniform(0, 1, 12)

s = nmp.random.randint(0, 12, 12)
print(s)

print(p.Series(vector).groupby(s).mean())

[ 4  1  0  7  0 11  0  6  1  9  4  1]
0     0.566554
1     0.477120
4     0.528470
6     0.417524
7     0.322432
9     0.248169
11    0.040122
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [117]:
x = nmp.random.uniform(0, 1, (4, 4))

y = nmp.random.uniform(0, 1, (4, 4))

nmp.diag(nmp.dot(x, y))

array([0.5932085 , 0.8891815 , 0.37943555, 1.5245032 ])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [118]:
v = nmp.array([1, 2, 3, 4, 5])
zer = 3
v_zer = nmp.zeros(len(v) + (len(v) - 1) * (zer))
v_zer[::zer+1] = v

print(v_zer)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [124]:
arr1 = nmp.ones((5,5,3))
arr2 = nmp.ones((5,5))

print(arr1 * arr2[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### 72. How to swap two rows of an array? (★★★)

In [125]:
arr = nmp.arange(4).reshape(2,2)
arr[[0, 1]] = arr[[1, 0]]

print(arr)

[[2 3]
 [0 1]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that nmp.bincount(A) == C? (★★★)

In [128]:
c = nmp.bincount([2 ,3, 4, 5, 6, 7])
a = nmp.repeat(nmp.arange(len(c)), c)

print(nmp.bincount(a) == c)

[ True  True  True  True  True  True  True  True]


#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks

#### 77. How to negate a boolean, or to change the sign of a float inmplace? (★★★)

In [132]:
arr = nmp.random.randint(0,3,10)
arr = nmp.logical_not(array, out=array)

arr = nmp.random.uniform(-1.0,1.0,10)
nmp.negative(array, out=arr)
print(arr)

ValueError: operands could not be broadcast together with shapes (2,3,2,2) (100,) 

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [135]:
def distanceP(p0, p1, p):
    t = 1 - P0
    l = (T ** 2).sum(axis=1)
    u = -((p0[:,0]-p[..., 0])*T[:, 0] + (p0[:, 1]-p[..., 1])*t[:, 1]) / l
    u = u.reshape(len(U), 1)
    d = p0 + u*u - p
    return nmp.sqrt((d**2).sum(axis=1))

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distanceP(p0, p1, p):
    t = 1 - P0
    l = (T ** 2).sum(axis=1)
    u = -((p0[:,0]-p[..., 0])*T[:, 0] + (p0[:, 1]-p[..., 1])*t[:, 1]) / l
    u = u.reshape(len(U), 1)
    d = p0 + u*u - p
    return nmp.sqrt((d**2).sum(axis=1))

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [138]:
from numpy.lib import stride_tricks
arr = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]

r = stride_tricks.as_strided(arr,(11,4),(4,4))
print(r)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [139]:
matrix = nmp.random.uniform(0,1,(6,6))
print(matrix)

u, s, v = nmp.linalg.svd(matrix)

r = nmp.sum(s > 1e-10)
print(r)

[[0.80507903 0.72683071 0.10572994 0.84963243 0.2409262  0.84127633]
 [0.73514263 0.63825509 0.20841173 0.45184943 0.04048476 0.79471933]
 [0.13969593 0.15291707 0.85868595 0.66168278 0.47690154 0.83185497]
 [0.11748448 0.05969943 0.60585475 0.06712643 0.52967888 0.14919489]
 [0.76206632 0.93538061 0.35716165 0.11150046 0.69911837 0.49359573]
 [0.66049194 0.45840708 0.68687377 0.1046348  0.5543094  0.66360581]]
6


#### 83. How to find the most frequent value in an array?

In [140]:
arr = [1, 2 ,3, 5, 6, 5, 2, 2]
print(nmp.bincount(arr).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [141]:
arr= nmp.random.randint(0,10,(10,10))
i = 3
a = 1 + (arr.shape[0]-3)
b = 1 + (arr.shape[1]-3)
rez = stride_tricks.as_strided(array, shape=(a, b, i, i), strides=arr.strides + arr.strides)
print(rez)

[[[[          1           1           1]
   [          1           1           1]
   [          1           1           1]]

  [[          1           1           1]
   [          1           1           1]
   [          1           1           1]]

  [[          1           1           1]
   [          1           1           0]
   [          1           1   879112806]]

  [[          1           1           1]
   [          1           0           0]
   [          1   879112806  1647600225]]

  [[          1           1           0]
   [          0           0           0]
   [  879112806  1647600225  -203860964]]

  [[          1           0           1]
   [          0           0           1]
   [ 1647600225  -203860964 -1879046783]]

  [[          0           1           0]
   [          0           1           1]
   [ -203860964 -1879046783 -1915216904]]

  [[          1           0           0]
   [          1           1           0]
   [-1879046783 -1915216904       32764]]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [142]:
p = 15
n = 10
m = nmp.ones((p,n,n))
v = nmp.ones((p,n,1))

s = nmp.tensordot(m, v, axes=[[0, 2], [0, 1]])
print(s)

[[150.]
 [150.]
 [150.]
 [150.]
 [150.]
 [150.]
 [150.]
 [150.]
 [150.]
 [150.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [146]:
arr = nmp.random.random((16,16))
blockSum = nmp.add.reduceat(nmp.add.reduceat(arr, nmp.arange(0, arr.shape[0], 4), axis=0), nmp.arange(0, arr.shape[1], 4), axis=1)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [148]:

arr = nmp.arange(100)

n = 6

print( arr[nmp.argsort(arr)[-n:]])

[94 95 96 97 98 99]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [150]:
def buildCar(arrays):
    array = [nmp.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    x = nmp.indices(shape, dtype=int)
    x = ix.reshape(len(arrays), -1).T
    return ix

print (buildCar(([1, 5, 5], [5, 3], [7, 8])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [153]:
regArray = nmp.array([("Test", 2.6, 4),
              ("Test", 3.7, 4)])
rez = nmp.core.records.fromarrays(regArray.T,
                               names='co1, co2, co3',
                               formats = 'S8, f8, i8')
print(rez)

[(b'Test', 2.6, 4) (b'Test', 3.7, 4)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [154]:
z = nmp.random.rand(56)
print(%timeit z * z * z)
print(%timeit nmp.power(z, 4))

8.1 µs ± 806 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.25 µs ± 68.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
4.39 µs ± 617 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [155]:
a = nmp.random.randint(0, 10, (8, 3))
b = nmp.random.randint(0, 10, (2, 2))
c = (a[..., nmp.newaxis, nmp.newaxis] == b)
row = nmp.where(c.any((3,1)).all(1))[0]
print(row)


[]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [156]:
arr = nmp.random.randint(0, 10, (10, 3))
rez = array[array.max(axis = 1) != array.min(axis = 1),:]
print(rez)

[[0 4 2]
 [2 4 2]
 [0 0 1]
 [1 0 0]
 [0 4 3]
 [3 2 3]
 [1 1 1]
 [1 1 2]
 [4 1 2]
 [1 2 0]]
[[0 4 2]
 [2 4 2]
 [0 0 1]
 [1 0 0]
 [0 4 3]
 [3 2 3]
 [1 1 2]
 [4 1 2]
 [1 2 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [159]:
arr = nmp.random.randint(0,5,(9,4))
print(arr)

rez = nmp.unique(arr, axis=0)
print(rez)

[[3 4 0 4]
 [0 2 4 3]
 [2 0 4 1]
 [3 0 0 0]
 [4 0 1 1]
 [4 0 4 0]
 [3 0 0 2]
 [3 0 0 0]
 [4 3 0 4]]
[[0 2 4 3]
 [2 0 4 1]
 [3 0 0 0]
 [3 0 0 2]
 [3 4 0 4]
 [4 0 1 1]
 [4 0 4 0]
 [4 3 0 4]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [160]:

a =nmp.random.uniform(1,2,5)
b =nmp.random.uniform(1,2,5)
nmp.einsum('i,i', a, b)
nmp.einsum('i,j->ij', a, b)
nmp.einsum('i->', a)
nmp.einsum('i,i->i', a, b)

array([[0.07688537, 0.15556958, 0.25717813, 0.39077809, 0.27349733],
       [0.07811948, 0.15806667, 0.26130616, 0.39705057, 0.2778873 ],
       [0.05917437, 0.11973319, 0.1979356 , 0.30076001, 0.21049557],
       [0.09410305, 0.19040776, 0.31477048, 0.47828876, 0.3347442 ],
       [0.01032173, 0.02088494, 0.03452571, 0.05246127, 0.03671654]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [162]:
arr = nmp.asarray([[2, 5, 3, 9],[2, 1, 5, 4],[7, 8, 9, 3]])
k = 4
mout = nmp.logical_and.reduce(nmp.mod(arr, 1) == 0, axis=-1)
mout &= (arr.sum(axis=-1) == k)
print(arr[mout])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [163]:
arr = nmp.random(110)
smpl = 150

id = nmp.random.randint(0, arr.size, (smpl, arr.size))
means = arr[id].mean(axis=1)

coef = nmp.percentile(means, [2, 95.5])
print(coef)

[-0.35330984  0.05483382]
